name: Deploy Managed Application
run-name: Deploying Managed solution ${{ github.event.inputs.solution_name }} for ${{ github.event.inputs.environment_url }} environment
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Provide the solution name you want to deploy"
        required: true
        default: ALMLab
      # environment_id:
      #   description: "GUID of your Dataverse environment"
      #   required: true
      #   default: "GUID-OF-YOUR-ENVIRONMENT"
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https:githubactionsbuild.crm.dynamics.com"
      solution_source_folder:
        description: "Location of the solution files"
        required: true
        default: solutions/
      solution_outbound_folder:
        description: "solution outbound folder"
        required: true
        default: out/stage

env:
#edit your values here
  ENVIRONMENT_URL: https://orgc5bad68d.crm.dynamics.com
  CLIENT_ID: ${{secrets.appID}}
  TENANT_ID: ${{secrets.TENANTID}}
permissions:
  contents: write
jobs:
    import-managed-solution:
      runs-on: windows-latest
      env:
        RUNNER_DEBUG: 1
      steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{env.ENVIRONMENT_URL}}
          user-name: ${{env.USERNAME}}
          password-secret: ${{ secrets.password }}
        
      - name: Import solution as managed to build env
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{github.event.inputs.environment_url}}
          app-id: ${{secrets.appID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{secrets.tenantID}}
          solution-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}_managed.zip
          force-overwrite: true
          publish-changes: true
    
